ViewModels/Login.cs
using System.ComponentModel.DataAnnotations;

namespace Assignment.ViewModels
{
    public class Login
    {
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        public bool RememberMe { get; set; }
    }
}

ViewModels/Register.cs
using System.ComponentModel.DataAnnotations;
using System.Text.RegularExpressions;

namespace Assignment.ViewModels
{
    public class Register
    {
		[Required]
		[DataType(DataType.Text)]
		public string FirstName { get; set; }
		[Required]
		[DataType(DataType.Text)]
		public string LastName { get; set; }
		[Required]
		[DataType(DataType.CreditCard)]
		public string CreditCardNo { get; set; }
		[Required]
		[DataType(DataType.PhoneNumber)]
		public string MobileNo { get; set; }
		[Required]
		[DataType(DataType.Text)]
		public string BillingAddress { get; set; }
		[Required]
		[DataType(DataType.Text)]
		public string ShippingAddress { get; set; }
		[Required]
		[DataType(DataType.EmailAddress)]
		public string EmailAddress { get; set; }
		[Required]
		[DataType(DataType.Password)]
		public string Password { get; set; }
		[Required]
		[DataType(DataType.Password)]
		public string ConfirmPassword { get; set; }

		// TODO: Add photo
		[Required]
		public IFormFile Image { get; set; }
	}
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Assignment.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using Assignment.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System.Security.Claims;
using System.Text;

namespace Assignment.Pages
{
    [Authorize]
    [ValidateAntiForgeryToken]
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private UserManager<MemberIdentityUser> userManager { get; }

        private readonly SignInManager<MemberIdentityUser> signInManager;

        public IndexModel(ILogger<IndexModel> logger, UserManager<MemberIdentityUser> userManager, SignInManager<MemberIdentityUser> signInManager)
        {
            _logger = logger;
            this.userManager = userManager;
            this.signInManager = signInManager;
        }

        public async Task OnGet()
        {

            if (User != null && userManager.Users.Count() > 0)
            {
                // Log out for multiple sessions
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                var user = userManager.Users.ToList().Find(t=> t.Id == userId);

                // log out user if security stamp not match cookie, WILL LOGOUT IF COOKIE IS NULL
                if (Request.Cookies["AuthCookie"] != null && user!.SecurityStamp != Request.Cookies["AuthCookie"]!.ToString())
                {
                    HttpContext.Session.Clear();
                    Response.Cookies.Delete("AuthCookie");
                    await signInManager.SignOutAsync();
                }

                var dataProtectionProvider = DataProtectionProvider.Create("EncryptData");
                var protector = dataProtectionProvider.CreateProtector("SecretKey");

                HttpContext.Session.SetString("FirstName", protector.Unprotect(decoder(user.FirstName)));
                HttpContext.Session.SetString("LastName", protector.Unprotect(decoder(user.LastName)));
                HttpContext.Session.SetString("CreditCard", protector.Unprotect(decoder(user.CreditCardNo)));
                HttpContext.Session.SetString("PhoneNumber", protector.Unprotect(decoder(user.MobileNumber)));
                HttpContext.Session.SetString("BillingAddress", protector.Unprotect(decoder(user.BillingAddress)));
                HttpContext.Session.SetString("Email", user.UserName);
                HttpContext.Session.SetString("Password", user.PasswordHash);
                HttpContext.Session.SetString("FilePath", $"uploads/{protector.Unprotect(user.ImagePath)}");

                HttpContext.Session.SetString("AuthToken", user.SecurityStamp);
            }
        }

        private string decoder(byte[] encodedBytes)
        {
            string decodedString = Encoding.ASCII.GetString(encodedBytes);

            return decodedString;
        }
    }
}

Pages/Login.cshtml.cs
using Assignment.Model;
using Assignment.ViewModels;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Security.Claims;
using System.Text;
using System.Text.RegularExpressions;

namespace Assignment.Pages
{
    public class LoginModel : PageModel
    {
		[BindProperty]
		public Login LModel { get; set; }

		private readonly SignInManager<MemberIdentityUser> signInManager;
        private readonly UserManager<MemberIdentityUser> userManager;
        private readonly ILogger<IndexModel> _logger;
        public LoginModel(ILogger<IndexModel> logger, SignInManager<MemberIdentityUser> signInManager, UserManager<MemberIdentityUser> userManager)
		{
            _logger = logger;
			this.signInManager = signInManager;
            this.userManager = userManager;
		}

		public void OnGet()
        {
        }

		public async Task<IActionResult> OnPostAsync()
		{
			if (ModelState.IsValid)
			{
                if (checkInvalidChar())
                {
                    ModelState.AddModelError("", "Invalid characters");
                }
                else
                {
                    // do sign in
                    var identityResult = await signInManager.PasswordSignInAsync(LModel.Email, LModel.Password, LModel.RememberMe, true);
                    // user is locked out
                    if (identityResult.IsLockedOut)
                    {
                        ModelState.AddModelError("", "Locked out");
                    }

                    if (identityResult.Succeeded)
				    {
                        // get logged in user
                        var loggedInUser = await userManager.FindByNameAsync(LModel.Email);
                        if (loggedInUser != null)
                        {
                            await userManager.UpdateSecurityStampAsync(loggedInUser);

                            // Add a cookie with same Guid value
                            CookieOptions options = new CookieOptions();
                            options.Secure = true;
                            options.HttpOnly = true;
                            Response.Cookies.Append("AuthCookie", loggedInUser.SecurityStamp, options);
                        }
                        return RedirectToPage("Index");
				    }
				    ModelState.AddModelError("", "Username or Password incorrect");
                }
			}
			return Page();
		}

        private bool checkInvalidChar()
        {
            if (Regex.Matches(LModel.Email, @"[*&%#$^!]").Count > 0)
            {
                return true;
            }
            return false;
        }
    }
}

Pages/Logout.cshtml.cs
using Assignment.Model;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Assignment.Pages
{
    public class LogoutModel : PageModel
    {
		private readonly SignInManager<MemberIdentityUser> signInManager;

		public LogoutModel(SignInManager<MemberIdentityUser> signInManager)
		{
			this.signInManager = signInManager;
		}

		public void OnGet() { }

		public async Task<IActionResult> OnPostLogoutAsync()
		{
            // clear all session
            HttpContext.Session.Clear();
			HttpContext.Session.Remove("AspNetCore.Session");
			HttpContext.Session.Remove("AspNetCore.Antiforgery");
            Response.Clear();

            Response.Cookies.Delete("AuthCookie");

            await signInManager.SignOutAsync();
			return RedirectToPage("Login");
		}
		public async Task<IActionResult> OnPostDontLogoutAsync()
		{
			return RedirectToPage("Index");
		}
	}
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Assignment.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Register.cshtml.cs
using Assignment.Model;
using Assignment.ViewModels;
using Microsoft.AspNetCore.CookiePolicy;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Primitives;
using System;
using System.Drawing;
using System.Security.Claims;
using System.Text;
using System.Text.RegularExpressions;

namespace Assignment.Pages
{
	public class RegisterModel : PageModel
	{
		private UserManager<MemberIdentityUser> userManager { get; }
		private SignInManager<MemberIdentityUser> signInManager { get; }
        private readonly IWebHostEnvironment _environment;

        private readonly ILogger<IndexModel> _logger;

        [BindProperty]
		public Register RModel { get; set; }

		public RegisterModel(ILogger<IndexModel> logger, UserManager<MemberIdentityUser> userManager,
		SignInManager<MemberIdentityUser> signInManager, IWebHostEnvironment environment)
		{
			_logger = logger;
			this.userManager = userManager;
			this.signInManager = signInManager;
            _environment = environment;
        }

		public void OnGet()
		{
            var password = HttpContext.Session.GetString("pwd");
			if (password == null)
			{
				password = "";
			}
            var strength = "";
			if (checkPassword(password) == 1) {
				strength = "Weak";
			}
            if (checkPassword(password) == 2)
            {
                strength = "Weak";
            }
            if (checkPassword(password) == 3)
            {
                strength = "Medium";
            }
            if (checkPassword(password) == 4)
            {
                strength = "Medium";
            }
            if (checkPassword(password) == 5)
            {
                strength = "Strong";
            }
            HttpContext.Session.SetString("pwdStrength", strength);
        }

		//Save data into the database
		public async Task<IActionResult> OnPostAsync()
		{

            if (ModelState.IsValid && checkPassword(RModel.Password) == 5)
			{
				if (checkInvalidChar())
				{
					ModelState.AddModelError("", "Invalid characters");
				}
				else
				{
                    // Add Image
                    var path = Path.Combine(_environment.WebRootPath, "uploads", RModel.Image.FileName);
                    using (FileStream stream = new FileStream(path, FileMode.Create))
                    {
                        await RModel.Image.CopyToAsync(stream);
                        stream.Close();
                    }

                    var dataProtectionProvider = DataProtectionProvider.Create("EncryptData");
					var protector = dataProtectionProvider.CreateProtector("SecretKey");

					// check if email already exists
					var user_emails = userManager.Users.ToList().Select(t=> t.Email);

					// guid for session
					var guid = Guid.NewGuid().ToString();

					if (!user_emails.Contains(RModel.EmailAddress))
					{

                        // TODO: NEED TO PROTECT USERNAME?
                        var user = new MemberIdentityUser()
						{
							UserName = RModel.EmailAddress,
							FirstName = encoder(protector.Protect(RModel.FirstName)),
							LastName = encoder(protector.Protect(RModel.LastName)),
							CreditCardNo = encoder(protector.Protect(RModel.CreditCardNo)),
							MobileNumber = encoder(protector.Protect(RModel.MobileNo)),
							BillingAddress = encoder(protector.Protect(RModel.BillingAddress)),
							ShippingAddress = encoder(protector.Protect(RModel.ShippingAddress)),
							ImagePath = protector.Protect(RModel.Image.FileName)
						};
						var result = await userManager.CreateAsync(user, RModel.Password);
						if (result.Succeeded)
						{
							await signInManager.SignInAsync(user, false);

                            // get logged in user
                            var loggedInUser = await userManager.FindByNameAsync(RModel.EmailAddress);
                            if (loggedInUser != null)
                            {
                                await userManager.UpdateSecurityStampAsync(loggedInUser);

                                // Add a cookie with same Guid value
                                CookieOptions options = new CookieOptions();
                                options.Secure = true;
                                options.HttpOnly = true;
                                Response.Cookies.Append("AuthCookie", loggedInUser.SecurityStamp, options);
                            }

                            return RedirectToPage("Index");
						}
						foreach (var error in result.Errors)
						{
							ModelState.AddModelError("", error.Description);
						}
					}
					ModelState.AddModelError("", "A user already has that email");
				}
			}
			return Page();
		}

        private byte[] encoder(string originalString)
        {
            byte[] encodedBytes = Encoding.ASCII.GetBytes(originalString);

            return encodedBytes;
        }

        private bool checkInvalidChar()
		{
			if (Regex.Matches(RModel.FirstName, @"[*&%#@$^!]").Count > 0)
			{
				return true;
			}
            if (Regex.Matches(RModel.LastName, @"[*&%#@$^!]").Count > 0)
            {
                return true;
            }
            if (Regex.Matches(RModel.CreditCardNo, @"[*&%#@$^!]").Count > 0)
            {
                return true;
            }
            if (Regex.Matches(RModel.MobileNo, @"[*&%#@$^!]").Count > 0)
            {
                return true;
            }
            if (Regex.Matches(RModel.BillingAddress, @"[*&%#@$^!]").Count > 0)
            {
                return true;
            }
            if (Regex.Matches(RModel.ShippingAddress, @"[*&%#@$^!]").Count > 0)
            {
                return true;
            }
            return false;
		}

		private int checkPassword(string password)
		{
			int score = 0;

			// Score 0
			if (password.Length < 8) return 1;
			else score = 1;

			// Score 2
			if (Regex.IsMatch(password, "[a-z]"))
			{
				score++;
			}

			// Score 3
			if (Regex.IsMatch(password, "[A-Z]"))
			{
				score++;
			}

			// Score 4
			if (Regex.IsMatch(password, "[0-9]"))
			{
				score++;
			}

			// Score 5
			if (Regex.IsMatch(password, "[`!@#$%^&*()_+\\-=\\[\\]{};':\"\\\\|,.<>\\/?~]"))
			{
				score++;
			}

			return score;
		}
	}
}

Pages/Index.cshtml
@page
@model IndexModel

@using Microsoft.AspNetCore.Http
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>

    <ul>
        <li>First Name: @HttpContext.Session.GetString("FirstName")</li>
        <li>Last Name: @HttpContext.Session.GetString("LastName")</li>
        <li>Credit Card Number: @HttpContext.Session.GetString("CreditCard")</li>
        <li>Mobile Number: @HttpContext.Session.GetString("PhoneNumber")</li>
        <li>Billing Address: @HttpContext.Session.GetString("BillingAddress")</li>
        <li>Email: @HttpContext.Session.GetString("Email")</li>
        <li>Password: @HttpContext.Session.GetString("Password")</li>
        <li><img src="@HttpContext.Session.GetString("FilePath")"></li>

        <li>Session: @HttpContext.Session.GetString("AuthToken")</li>
        <li>Cookie: @Request.Cookies["AuthCookie"]</li>
    </ul>
</div>

Pages/Login.cshtml
@page
@model Assignment.Pages.LoginModel
@{
}
<script src="https://www.google.com/recaptcha/api.js"></script>
<script>
	function onSubmit(token) {
		document.getElementById("login-form").submit();
	}
</script>

<div class="container mt-5">

	<div class="row justify-content-center align-items-center">

		<div class="col-sm-12 col-md-12 col-lg-4">
			<h1 class="mb-3">Login </h1>

			<form method="post" id="login-form">
				<div asp-validation-summary="All" class="text-danger"></div>

				<div class="mb-3">
					<label class="form-label" asp-for="LModel.Email">Email Address</label>
					<input type="Text" asp-for="LModel.Email" class="form-control" />
					<span asp-validaton-for="LModel.Email" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="LModel.Password">Password</label>
					<input type="Text" asp-for="LModel.Password" class="form-control" />
					<span asp-validaton-for="LModel.Password" class="text-danger"></span>
				</div>

				<div class="mb-3 form-check">
					<input type="checkbox" asp-for="LModel.RememberMe" class="form-check-input" />
					<label class="form-check-label" asp-for="LModel.RememberMe">Remember Me?</label>
				</div>

				<div class="mb-3">
					<button type="submit" 
						class="btn btn-primary g-recaptcha"
						data-sitekey="6LfyXlgpAAAAAFUKlF6FNFvjCWHEbPdIdjrcRXIS"
						data-callback='onSubmit'
						data-action='submit'>
						Login
					</button>
				</div>
			</form>
		</div>
	</div>
</div>

Pages/Logout.cshtml
@page
@model Assignment.Pages.LogoutModel
@{
}

<form method="post">
	<div class="container mt-5">
		<div class="row justify-content-center">
			<div class="col-sm-12 col-md-12 col-lg-4">
				<p> Are you sure you want to logout? </p>
				<p>
					<button class="btn btn-primary" asp-page-handler="Logout">Yes</button>
					<button class="btn btn-light ml-5 border-dark" asp-page-handler="DontLogout">No</button>
				</p>
			</div>
		</div>
	</div>
</form>

Pages/Register.cshtml
@page
@model Assignment.Pages.RegisterModel
@{
}

@using Microsoft.AspNetCore.Http

<script src="https://www.google.com/recaptcha/api.js"></script>
<script>
    function onSubmit(token) {
        document.getElementById("register-form").submit();
    }
</script>

<script type="text/javascript">

    function checkUpper(string) {
        return /[A-Z]/.test(string);
    }

    var scoreChecker = { pwdlength: false, pwdnumber: false, pwdupper: false, pwdlower: false, pwdspecial: false }

    function validate() {
        var str = document.getElementById('tb_password').value;

        // check if 8 characters
        if (str.length < 8) {
            document.getElementById("lbl_pwdlength").innerHTML = "Password Length must be at least 8 characters";
            document.getElementById("lbl_pwdlength").style.color = "Red";
            if (scoreChecker["pwdlength"]) {
                scoreChecker["pwdlength"] = false;
                console.log("test")
            }
        }
        else {
            document.getElementById("lbl_pwdlength").innerHTML = "Password length is good"
            document.getElementById("lbl_pwdlength").style.color = "Blue";
            if (!scoreChecker["pwdlength"]) {
                scoreChecker["pwdlength"] = true;
            }
        }

        // check if got number
        if (str.search(/[0-9]/) == -1) {
            document.getElementById("lbl_pwdnumber").innerHTML = "Password require at least 1 number";
            document.getElementById("lbl_pwdnumber").style.color = "Red";
            if (scoreChecker["pwdnumber"]) {
                scoreChecker["pwdnumber"] = false;
            }
        }
        else {
            document.getElementById("lbl_pwdnumber").innerHTML = "Password has a number"
            document.getElementById("lbl_pwdnumber").style.color = "Blue";
            if (!scoreChecker["pwdnumber"]) {
                scoreChecker["pwdnumber"] = true;
            }
        }

        // check if got uppercase
        if (!checkUpper(str)) {
            document.getElementById("lbl_pwdupper").innerHTML = "Password require at least 1 uppercase character";
            document.getElementById("lbl_pwdupper").style.color = "Red";
            if (scoreChecker["pwdupper"]) {
                scoreChecker["pwdupper"] = false;
            }
        }
        else {
            document.getElementById("lbl_pwdupper").innerHTML = "Password has uppercase"
            document.getElementById("lbl_pwdupper").style.color = "Blue";
            if (!scoreChecker["pwdupper"]) {
                scoreChecker["pwdupper"] = true;
            }
        }

        // require 1 lowercase
        if (str.search(/[a-z]/) == -1) {
            document.getElementById("lbl_pwdlower").innerHTML = "Password require at least 1 lowercase character";
            document.getElementById("lbl_pwdlower").style.color = "Red";
            if (scoreChecker["pwdlower"]) {
                scoreChecker["pwdlower"] = false;
            }
        }
        else {
            document.getElementById("lbl_pwdlower").innerHTML = "Password has lowercase"
            document.getElementById("lbl_pwdlower").style.color = "Blue";
            if (!scoreChecker["pwdlower"]) {
                scoreChecker["pwdlower"] = true;
            }
        }

        // require special character
        if (str.search(/[ `!@@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?~]/) == -1) {
            document.getElementById("lbl_pwdspecial").innerHTML = "Password require at least 1 special character";
            document.getElementById("lbl_pwdspecial").style.color = "Red";
            if (scoreChecker["pwdspecial"]) {
                scoreChecker["pwdspecial"] = false;
            }
        }
        else {
            document.getElementById("lbl_pwdspecial").innerHTML = "Password has special character"
            document.getElementById("lbl_pwdspecial").style.color = "Blue";
            if (!scoreChecker["pwdspecial"]) {
                scoreChecker["pwdspecial"] = true;
            }
        }

        strengthScore();
    }

    function strengthScore() {
        var score = Object.values(scoreChecker).filter((bool) => bool === true).length;
        var status = "";
        switch (score) {
            case 1:
                document.getElementById("lbl_pwdstrength").innerHTML = "Very Weak";
                document.getElementById("lbl_pwdstrength").style.color = "Red";
                break;
            case 2:
                document.getElementById("lbl_pwdstrength").innerHTML = "Weak";
                document.getElementById("lbl_pwdstrength").style.color = "Red";
                break;
            case 3:
                document.getElementById("lbl_pwdstrength").innerHTML = "Medium";
                document.getElementById("lbl_pwdstrength").style.color = "Orange";
                break;
            case 4:
                document.getElementById("lbl_pwdstrength").innerHTML = "Strong";
                document.getElementById("lbl_pwdstrength").style.color = "Orange";
                break;
            case 5:
                document.getElementById("lbl_pwdstrength").innerHTML = "Very Strong";
                document.getElementById("lbl_pwdstrength").style.color = "Green";
                break;

            default:
                break;
        }
    }

</script>

<div class="container mt-5">

	<div class="row justify-content-center align-items-center">

		<div class="col-sm-12 col-md-12 col-lg-4">
			<h1 class="mb-3">Register </h1>

            <form method="post" id="register-form" enctype="multipart/form-data">
				<div asp-validation-summary="All" class="text-danger"></div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.FirstName">First Name</label>
					<input type="Text" asp-for="RModel.FirstName" class="form-control" />
					<span asp-validaton-for="RModel.FirstName" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.LastName">Last Name</label>
					<input type="Text" asp-for="RModel.LastName" class="form-control" />
					<span asp-validaton-for="RModel.LastName" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.CreditCardNo">Credit Card Number</label>
                    <input type="Text" asp-for="RModel.CreditCardNo" class="form-control" />
					<span asp-validaton-for="RModel.CreditCardNo" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.MobileNo">Mobile Number</label>
					<input type="tel" asp-for="RModel.MobileNo" class="form-control" />
					<span asp-validaton-for="RModel.MobileNo" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.BillingAddress">Billing Address</label>
					<input type="Text" asp-for="RModel.BillingAddress" class="form-control" />
					<span asp-validaton-for="RModel.BillingAddress" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.ShippingAddress">Shipping Address</label>
					<input type="Text" asp-for="RModel.ShippingAddress" class="form-control" />
					<span asp-validaton-for="RModel.ShippingAddress" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.EmailAddress">Email Address</label>
					<input type="Text" asp-for="RModel.EmailAddress" class="form-control" />
					<span asp-validaton-for="RModel.EmailAddress" class="text-danger"></span>
				</div>

                <div class="mb-3">
                    <label class="form-label" asp-for="RModel.Image">Image</label>
                    <input type="file" asp-for="RModel.Image" class="form-control" />
                    <span asp-validaton-for="RModel.Image" class="text-danger"></span>
                </div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.Password">Password</label>
                    <input type="Text" asp-for="RModel.Password" class="form-control" ID="tb_password" onkeyup="javascript:validate()" />
					<span asp-validaton-for="RModel.Password" class="text-danger"></span>
				</div>

                <asp:Label ID="lbl_pwdlength" runat="server" Text="length"></asp:Label>
                <br />
                <asp:Label ID="lbl_pwdnumber" runat="server" Text="number"></asp:Label>
                <br />
                <asp:Label ID="lbl_pwdupper" runat="server" Text="upper"></asp:Label>
                <br />
                <asp:Label ID="lbl_pwdlower" runat="server" Text="lower"></asp:Label>
                <br />
                <asp:Label ID="lbl_pwdspecial" runat="server" Text="special"></asp:Label>
                <br />
                <asp:Label ID="lbl_pwdstrength" runat="server" Text="special"></asp:Label>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.ConfirmPassword">Confirm Password</label>
					<input type="Text" asp-for="RModel.ConfirmPassword" class="form-control" />
					<span asp-validaton-for="RModel.ConfirmPassword" class="text-danger"></span>
				</div>

				<div class="mb-3">
                    <button type="submit" class="btn btn-primary g-recaptcha"
                            data-sitekey="6LfyXlgpAAAAAFUKlF6FNFvjCWHEbPdIdjrcRXIS"
                            data-callback='onSubmit'>
                        Register
                    </button>
				</div>
			</form>
		</div>
	</div>
</div>